package com.abctreinamentos;
// Generated 02/01/2019 23:10:23 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "PAGAMENTO")
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Override
	public String toString() {
		return "Pagamento [id=" + id + ", datainscricao=" + datainscricao + "]";
	}

	private PagamentoId id;
	private String datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, String datainscricao) {
		this.id = id;
		this.datainscricao = datainscricao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cpf", column = @Column(name = "CPF", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "cdcurso", column = @Column(name = "CDCURSO", nullable = false, precision = 22, scale = 0)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@Column(name = "DATAINSCRICAO", nullable = false, length = 10)
	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}

}
